# Generated by Django 4.1.6 on 2023-02-16 21:10

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='avatar',
            field=stdimage.models.StdImageField(force_min_size=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Avatar'),
        ),
    ]
